name: build_mac

on:
#  push:
#     tags:
#        - '*'
#   push:
#      branches: [master]
    release:
       types:
          - created

jobs:
  extract_version:
     name: extract version name
     runs-on: ubuntu-latest
     steps:
       - name: echo
         run: |
            echo ${{github.event.release.tag_name}}
            echo ${{github.event.release.upload_url}}	  