name: build_mac

on:
#  push:
#     tags:
#        - '*'
#   push:
#      branches: [master]
    release:
       types:
          - created

jobs:
  extract_version:
     name: extract version name
     runs-on: ubuntu-latest
     steps:
       - name: echo
         run: |
           echo "TAG_VERSION=$(echo ${{github.event.release.tag_name}} | sed 's/[^0-9.]*//g')" >> $GITHUB_ENV
           echo ${{github.event.release.tag_name}}
           echo ${{github.event.release.upload_url}}
       - name: test
         run: |
           echo $TAG_VERSION
           echo sample > sample_out.txt
           tar -zcvf sample-"${TAG_VERSION}".tar.gz  sample_out.txt
           ls -l

       - name: Upload the bottle to the GitHub release
         uses: actions/upload-release-asset@v1.0.1
         env:
            GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.RELEASE }}
         with:
           upload_url: ${{ github.event.release.upload_url }}
           asset_path: ./sample-"${TAG_VERSION}".tar.gz
           asset_name: sample.tar.gz
           asset_content_type: application/gzip