name: test_data_passing

on:
#  push:
#     tags:
#        - '*'
   push:
      branches: [master]
#    release:
#       types:
#          - created

jobs:
  extract_version:
     name: install cuda
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
     
       - name: cuda
         run: |
           source ./ci_scripts/add_cuda_11_1.sh;	 
